#!/usr/bin/env ruby

pod 'UAAppReviewManager', :path => '../'

target 'UAAppReviewManagerExampleiOS' do
  platform :ios, '6.0'
end

target 'UAAppReviewManagerExampleMac' do
  platform :osx, '10.7'
end
