target 'UAAppReviewManagerExampleiOS' do
  platform :ios, '5.1'
  pod 'UAAppReviewManager', :path => '../'
end

target 'UAAppReviewManagerExampleMac' do
  platform :osx, '10.7'
  pod 'UAAppReviewManager', :path => '../'
end
